### ISSUE TITLE
Docker: Add docker compose examples

### ISSUE THREAD

**Issue by michael-wisely-gravwell** [gravwell/wiki#687]
## What needs to be done?

Add a docker-compose example to our Docker docs

## Why is this task needed? 

docker-compose makes it easier to configure/deploy applications that require multiple containers. 

I've been using them to define various Gravwell setups, and I think our users could benefit from some compose examples.

## Any other comments?

Below is an example that has a couple of ingesters configured. I've included a comment about configuring volumes for persistent storage.

Dropping this file in an empty directory and running `docker-compose up` (or `docker compose up` depending on your docker setup) is enough to start a Gravwell instance with some additional ingesters.

```yaml
---
version: "3.5"

networks:
  gravwell:

services:
  gravwell:
    image: "gravwell/gravwell:latest"
    restart: always
    ports:
      - 8080:80
    # Don't forget to configure your volumes, so that your data persists!
    # See https://docs.gravwell.io/configuration/docker.html#configuring-persistent-storage
    # volumes:
    networks:
      - gravwell
    environment:
      - GRAVWELL_INGEST_SECRET=MyIngestSecret
      - GRAVWELL_INGEST_AUTH=MyIngestSecret
      - GRAVWELL_CONTROL_AUTH=MyControlSecret
      - GRAVWELL_SEARCHAGENT_AUTH=MySearchAgentAuth

  simple-relay:
    image: "gravwell/simple_relay:latest"
    restart: always
    depends_on:
      - gravwell
    networks:
      - gravwell
    environment:
      - GRAVWELL_CLEARTEXT_TARGETS=gravwell 
      - GRAVWELL_INGEST_SECRET=MyIngestSecret

  netflow-capture:
    image: "gravwell/netflow_capture:latest"
    restart: always
    depends_on:
      - gravwell
    networks:
      - gravwell
    environment:
      - GRAVWELL_CLEARTEXT_TARGETS=gravwell 
      - GRAVWELL_INGEST_SECRET=MyIngestSecret

```
